#!/bin/sh -e

path_is=$(LC_ALL=C update-alternatives --display "${__object_id?}" 2>/dev/null \
    | awk '/link currently points to/ { print $5 }')

if test -n "${path_is}"
then
    echo "${path_is}"
else
    echo "unable to get current path for ${__object_id:?}" >&2
    exit 1
fi
